DROP TABLE IF EXISTS PRICES;
DROP SEQUENCE IF EXISTS ID_SEQUENCE;
CREATE SEQUENCE ID_SEQUENCE START WITH 1000 INCREMENT BY 1;

-- TABLE BRANDS
CREATE TABLE BRANDS
(
   ID BIGINT  NOT NULL,
   NAME VARCHAR(100) NOT NULL,
   PRIMARY KEY (ID)
);

-- TABLE PRICES
CREATE TABLE PRICES
(
   ID BIGINT  NOT NULL,
   PRODUCT_ID BIGINT NOT NULL,
   BRAND_ID BIGINT NOT NULL,
   PRIORITY INTEGER NOT NULL,
   START_DATE TIMESTAMP,
   PRICE NUMERIC(20,2) NOT NULL,
   CURR VARCHAR(3) NOT NULL,
   END_DATE TIMESTAMP,
   PRICE_LIST INTEGER NOT NULL,
   PRIMARY KEY (ID)
);

 ALTER TABLE PRICES
    ADD FOREIGN KEY (BRAND_ID)
    REFERENCES BRANDS(ID);